export const fakeUniversityData = [
  { universidad: "University of Madrid" },
  { universidad: "University of Barcelona" },
  { universidad: "University of Valencia" },
  { universidad: "University of Seville" },
  { universidad: "University of Granada" },
  { universidad: "University of Malaga" },
  { universidad: "University of Salamanca" },
  { universidad: "University of Zaragoza" },
  { universidad: "University of Oviedo" },
  { universidad: "University of Valladolid" },
  { universidad: "University of Murcia" },
  { universidad: "University of Alicante" },
  { universidad: "University of Cordoba" },
  { universidad: "University of Cadiz" },
  { universidad: "University of Girona" },
  { universidad: "University of Lleida" },
  { universidad: "University of Jaen" },
  { universidad: "University of Castilla-La Mancha" },
  { universidad: "University of Extremadura" },
  { universidad: "University of the Balearic Islands" },
  // Add more universities here
];
